app: stock-wizard
service: stock-wizard

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  memorySize: 2048
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
        - "s3:PutObjectAcl"
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::stock-wizard"
        - "arn:aws:s3:::stock-wizard/*"
plugins:
  - serverless-offline
functions:
  create_stock_list:
    handler: handler.create_stock_list
    events:
      - schedule: rate(1 day)
